<li class="sidenav-head">Dashboard</li>
<li class="profile-admin">Hello : Yotsawatt</li>
<li><a href="mainpage">Home</a></li>
<li><a href="product">product</a></li>
<li><a href="aboutus">aboutus</a></li>
<li><a href="findastore">findastore</a></li>
<li><a href="contactus">contactus</a></li>
<li class="line-cut"></li>
<li><a href="productall">product</a></li>
<li><a href="certificate">certificate</a></li>
<li class="line-cut"></li>
<li><a href="profile">profile</a></li>
<li><a href="logout">Logout</a></li>